### ISSUE TITLE
Promoting a recurring job does not schedule the next job

### ISSUE THREAD

**Issue by jasonkim** [taskforcesh/bullmq#247]
I'm not sure if this is the expected behavior.
If I were to promote a recurring job, it should run it and then ideally queue the next job.

**Comment by manast** [comment]
It should work, since a recurring job is waiting as a delayed job, can you provide a test where this does not hold?

**Comment by jasonkim** [comment]
Finally got around to create a simple case.

```
import ioredis from 'ioredis'
import bullmq from 'bullmq'
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
async function test() {
  const { Queue, QueueScheduler, Worker, Job } = bullmq
  const connection = new ioredis()

  // bull-board
  const { setQueues } = bullboard

  const testq = new Queue('test', {connection})
  testq.add('recurring', {}, { repeat: { cron: '* * * * *' } })
  setQueues([testq])
  new QueueScheduler('test')

  new Worker('test', async job => {
    console.log(Date())
    console.log(job.id)
  })

  await sleep(90000)
  console.log(await testq.getDelayedCount())
  const jobs = await testq.getDelayed()
  const job = jobs[0]
  // console.log(job)
  job.promote()
  console.log("Promoted")
  await sleep(1000)
  console.log(await testq.getDelayedCount())

}
test()
```

I'm using a bull-board, but you can comment that out as that is not very important.
It should print the datetime and jobid every time the worker runs, but after promotion, it stops.
I've put in sleep function, but that's not very important and just shows that the recurring job works.

**Comment by Khauri** [comment]
Also noticed this issue. Promoting the job would run the process function, but the job would not be rescheduled afterwards. 
I had to work around this by essentially duplicating the data of the recurring job into a new job and adding that to the queue.

**Comment by manast** [comment]
I have reproduced this issue and know exactly why it happens, but I need some time to fix it.

**Comment by Khauri** [comment]
Thanks! In the meantime I've just done this and it works for my purposes:

```js
if(/^repeat:/.test(job.id)) {
  await queue.add(job.name, job.data);
} else {
  await job.promote();
}
```

But I do have a small question. When promoting a repeating job, say one that runs hourly with the next execution time being 10am, is the intended behavior to keep the scheduled time for the job as its next execution time (still 10am), or would it be to schedule it for the next hour afterwards (11am?).

**Comment by manast** [comment]
@Khauri it will be scheduled to the next run.

**Comment by janfietz** [comment]
I had the same issue. I promoted a repeating job with bull board. It disappeared from the delayed list and never came back.

**Comment by roggervalf** [comment]
Yeah, it's related to this line https://github.com/taskforcesh/bullmq/blob/master/src/commands/promote-5.lua#L20, where job is deleted from delayed list

**Comment by manast** [comment]
@fgozdz I think this issue has been resolved some time ago, specially with the new job scheduler, could you please verify that it works now with a new test case so that we can close this issue?

**Comment by EmilEriksen** [comment]
I'm currently experiencing this issue with the latest version (5.56.1). I have a simple every 900s job scheduler. If I promote the delayed job from the Taskforce dashboard no new delayed job is created.

**Comment by EmilEriksen** [comment]
I actually have another service running an older version (5.52.2) where this does not happen.

**Comment by manast** [comment]
@EmilEriksen actually I do not think the delayed job will be created directly, it will promote the current delayed job to wait status, and as soon as it is picked up by a worker a new delayed job will created instead.

**Comment by EmilEriksen** [comment]
@manast From what I can tell in the UI no new job is ever created even after the promoted job is processed. I can still see the scheduler under "Schedulers" but in Next job it just says X minutes ago.

**Comment by manast** [comment]
@EmilEriksen yes, I can reproduce an issue. A job that is promoted, when processed will not generate a new delayed job.

**Comment by manast** [comment]
in other words, it will break the iterations... we will start working on a fix now that we can reproduce it.

**Comment by manast** [comment]
The fix is coming in this PR: https://github.com/taskforcesh/bullmq/pull/2944
